### ISSUE TITLE
 morphbank3/www/docs/mb3a.xls

### ISSUE THREAD

**Issue by debpaul** [idiginfo/morphbank3#2]
File is corrupt. A user cannot open this successfully in Excel. Monika and I are cleaning up a new version to commit.

**Comment by monika297** [comment]
I have already commited the non-corrupted version of Excel file which Deb gave me long back. I think Robert should pull the changes from GitHub on the sky server to see the file properly.

**Comment by rbruhn** [comment]
Was this pushed to the github dev branch first? Should we pull to dev server and test there before pulling to production? Do we even have a dev anymore?

**Comment by debpaul** [comment]
I don't think DEV is up again, yet.

**Comment by rbruhn** [comment]
Ok... so was the push to the dev or master repo?

**Comment by monika297** [comment]
The push is done to the master repo (https://github.com/idiginfo/morphbank3).

**Comment by rbruhn** [comment]
I did the pull to the server if someone wants to check it. If it works, then please close this.

**Comment by monika297** [comment]
Thanks, Robert!! I have checked it. It is working fine. 
Closing the ticket.
